# Site settings
title: Andre Esteva's Blog
email:
description: > # this means to ignore newlines until "baseurl:"
  For non-peer reviewed non-publications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: andreesteva
github_username: andreesteva

# Build settings
markdown: kramdown
